### PR TITLE
Fix NullPointerException on swapCursor for IterableCursorAdapter

### LINKED ISSUE #10: LoaderCallbacks.onLoaderReset & NPE
I’m resetting cursor at `LoaderCallbacks#onLoaderReset` as [described at the documentation](http://developer.android.com/guide/components/loaders.html#callback). Unfortunately this action fails for `IterableCursorAdapter`. Trace is below for `cursor-utils:0.3`.

Actually I’m not sure why it happens because `instance of` check [should work just fine with `null` values](http://stackoverflow.com/a/2950415/3359826).

```
java.lang.RuntimeException: Unable to destroy activity: java.lang.NullPointerException
  at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3273)
  at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3291)
  at android.app.ActivityThread.access$1200(ActivityThread.java:130)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1248)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:137)
  at android.app.ActivityThread.main(ActivityThread.java:4745)
  at java.lang.reflect.Method.invokeNative(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:511)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
  at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
  at com.venmo.cursor.support.IterableCursorAdapter.enforceIterableCursor(IterableCursorAdapter.java:62)
  at com.venmo.cursor.support.IterableCursorAdapter.swapCursor(IterableCursorAdapter.java:44)
  at application.id.fragment.ListFragment.onLoaderReset(ListFragment.java:74)
  at android.support.v4.app.LoaderManagerImpl$LoaderInfo.destroy(LoaderManager.java:339)
  at android.support.v4.app.LoaderManagerImpl.doDestroy(LoaderManager.java:776)
  at android.support.v4.app.Fragment.onDestroy(Fragment.java:1202)
  at android.support.v4.app.Fragment.performDestroy(Fragment.java:2006)
  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1076)
  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
  at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:1954)
  at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:313)
  at android.support.v7.app.ActionBarActivity.onDestroy(ActionBarActivity.java:169)
  at android.app.Activity.performDestroy(Activity.java:5172)
  at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1109)
  at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3260)
  at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3291)
  at android.app.ActivityThread.access$1200(ActivityThread.java:130)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1248)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:137)
  at android.app.ActivityThread.main(ActivityThread.java:4745)
  at java.lang.reflect.Method.invokeNative(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:511)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
  at dalvik.system.NativeStart.main(Native Method)
```

### PR DESCRIPTION
**Pull request by ronshapiro**
Fixes #10

### CODE REVIEW

**Comment by ming13** [comment]
Hey guys, any chance to promote it to Central?

**Comment by ronshapiro** [comment]
Ah, yes, I thought this was included in `0.3`. I'll push `0.4` now

**Comment by ronshapiro** [comment]
0.4 is pushed (#18), should be synced with Central soon.

**Comment by ming13** [comment]
Thanks!

**Pull request merged**
